// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { CreateConnectionData, CreateConnectionErrors, CreateConnectionResponses, GetConnectionData, GetConnectionErrors, GetConnectionResponses, GetEntitiesData, GetEntitiesErrors, GetEntitiesResponses, Health2Data, Health2Responses, HealthData, HealthResponses, ListConnectionsData, ListConnectionsResponses, UploadFileData, UploadFileErrors, UploadFileResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List Connections
 */
export const listConnections = <ThrowOnError extends boolean = false>(options?: Options<ListConnectionsData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListConnectionsResponses, unknown, ThrowOnError>({
        url: '/connections',
        ...options
    });
};

/**
 * Create Connection
 */
export const createConnection = <ThrowOnError extends boolean = false>(options: Options<CreateConnectionData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateConnectionResponses, CreateConnectionErrors, ThrowOnError>({
        url: '/connections',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get Connection
 */
export const getConnection = <ThrowOnError extends boolean = false>(options: Options<GetConnectionData, ThrowOnError>) => {
    return (options.client ?? client).get<GetConnectionResponses, GetConnectionErrors, ThrowOnError>({
        url: '/connections/{connection_uid}',
        ...options
    });
};

/**
 * Get Entities
 */
export const getEntities = <ThrowOnError extends boolean = false>(options: Options<GetEntitiesData, ThrowOnError>) => {
    return (options.client ?? client).get<GetEntitiesResponses, GetEntitiesErrors, ThrowOnError>({
        url: '/connections/{connection_id}/entities',
        ...options
    });
};

/**
 * Upload File
 */
export const uploadFile = <ThrowOnError extends boolean = false>(options: Options<UploadFileData, ThrowOnError>) => {
    return (options.client ?? client).post<UploadFileResponses, UploadFileErrors, ThrowOnError>({
        ...formDataBodySerializer,
        url: '/bucket',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    });
};

/**
 * Health
 */
export const health = <ThrowOnError extends boolean = false>(options?: Options<HealthData, ThrowOnError>) => {
    return (options?.client ?? client).get<HealthResponses, unknown, ThrowOnError>({
        url: '/health',
        ...options
    });
};

/**
 * Health
 */
export const health2 = <ThrowOnError extends boolean = false>(options?: Options<Health2Data, ThrowOnError>) => {
    return (options?.client ?? client).get<Health2Responses, unknown, ThrowOnError>({
        url: '/',
        ...options
    });
};
