// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, formDataBodySerializer, type Options as Options2, type RequestResult, type TDataShape } from './client';
import { client } from './client.gen';
import type { CreateConnectionData, CreateConnectionErrors, CreateConnectionResponses, CreateRequestData, CreateRequestErrors, CreateRequestResponses, DeleteConnectionData, DeleteConnectionErrors, DeleteConnectionResponses, DeleteRequestData, DeleteRequestErrors, DeleteRequestResponses, ExecuteQueryData, ExecuteQueryErrors, ExecuteQueryResponses, ExplainQueryData, ExplainQueryErrors, ExplainQueryResponses, ExportEntityData, ExportEntityErrors, ExportEntityResponses, GetConnectionData, GetConnectionErrors, GetConnectionResponses, GetConnectionStatusData, GetConnectionStatusErrors, GetConnectionStatusResponses, GetEntityColumnsData, GetEntityColumnsErrors, GetEntityColumnsResponses, GetEntityRowsData, GetEntityRowsErrors, GetEntityRowsResponses, GetEntityStatsData, GetEntityStatsErrors, GetEntityStatsResponses, GetRequestData, GetRequestErrors, GetRequestResponses, GetSchemasData, GetSchemasErrors, GetSchemasResponses, GetTablesData, GetTablesErrors, GetTablesResponses, GetVariablesData, GetVariablesErrors, GetVariablesResponses, HealthData, HealthResponses, ListConnectionsData, ListConnectionsResponses, ListRequestsData, ListRequestsErrors, ListRequestsResponses, SendRequestData, SendRequestErrors, SendRequestResponses, SetVariablesData, SetVariablesErrors, SetVariablesResponses, TestConnectionData, TestConnectionErrors, TestConnectionResponses, UpdateConnectionData, UpdateConnectionErrors, UpdateConnectionResponses, UpdateRequestData, UpdateRequestErrors, UpdateRequestResponses, UploadFileData, UploadFileErrors, UploadFileResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Test Connection
 *
 * Dial a connection before saving it, so a typo is caught here rather than
 * at the first query.
 */
export const testConnection = <ThrowOnError extends boolean = false>(options: Options<TestConnectionData, ThrowOnError>): RequestResult<TestConnectionResponses, TestConnectionErrors, ThrowOnError> => (options.client ?? client).post<TestConnectionResponses, TestConnectionErrors, ThrowOnError>({
    url: '/connections/test',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List Connections
 */
export const listConnections = <ThrowOnError extends boolean = false>(options?: Options<ListConnectionsData, ThrowOnError>): RequestResult<ListConnectionsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListConnectionsResponses, unknown, ThrowOnError>({ url: '/connections', ...options });

/**
 * Create Connection
 */
export const createConnection = <ThrowOnError extends boolean = false>(options: Options<CreateConnectionData, ThrowOnError>): RequestResult<CreateConnectionResponses, CreateConnectionErrors, ThrowOnError> => (options.client ?? client).post<CreateConnectionResponses, CreateConnectionErrors, ThrowOnError>({
    url: '/connections',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Connection
 */
export const deleteConnection = <ThrowOnError extends boolean = false>(options: Options<DeleteConnectionData, ThrowOnError>): RequestResult<DeleteConnectionResponses, DeleteConnectionErrors, ThrowOnError> => (options.client ?? client).delete<DeleteConnectionResponses, DeleteConnectionErrors, ThrowOnError>({ url: '/connections/{connection_uid}', ...options });

/**
 * Get Connection
 */
export const getConnection = <ThrowOnError extends boolean = false>(options: Options<GetConnectionData, ThrowOnError>): RequestResult<GetConnectionResponses, GetConnectionErrors, ThrowOnError> => (options.client ?? client).get<GetConnectionResponses, GetConnectionErrors, ThrowOnError>({ url: '/connections/{connection_uid}', ...options });

/**
 * Update Connection
 */
export const updateConnection = <ThrowOnError extends boolean = false>(options: Options<UpdateConnectionData, ThrowOnError>): RequestResult<UpdateConnectionResponses, UpdateConnectionErrors, ThrowOnError> => (options.client ?? client).put<UpdateConnectionResponses, UpdateConnectionErrors, ThrowOnError>({
    url: '/connections/{connection_uid}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Connection Status
 *
 * Dial the connection and report whether it answers, without running a query.
 */
export const getConnectionStatus = <ThrowOnError extends boolean = false>(options: Options<GetConnectionStatusData, ThrowOnError>): RequestResult<GetConnectionStatusResponses, GetConnectionStatusErrors, ThrowOnError> => (options.client ?? client).get<GetConnectionStatusResponses, GetConnectionStatusErrors, ThrowOnError>({ url: '/connections/{connection_uid}/status', ...options });

/**
 * Upload File
 */
export const uploadFile = <ThrowOnError extends boolean = false>(options: Options<UploadFileData, ThrowOnError>): RequestResult<UploadFileResponses, UploadFileErrors, ThrowOnError> => (options.client ?? client).post<UploadFileResponses, UploadFileErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/bucket',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Get Schemas
 *
 * List schemas for a connection. Backends without schemas return an empty list.
 */
export const getSchemas = <ThrowOnError extends boolean = false>(options: Options<GetSchemasData, ThrowOnError>): RequestResult<GetSchemasResponses, GetSchemasErrors, ThrowOnError> => (options.client ?? client).get<GetSchemasResponses, GetSchemasErrors, ThrowOnError>({ url: '/connection/{connection_id}/schema', ...options });

/**
 * Get Tables
 *
 * List the tables of a connection, optionally within a schema.
 */
export const getTables = <ThrowOnError extends boolean = false>(options: Options<GetTablesData, ThrowOnError>): RequestResult<GetTablesResponses, GetTablesErrors, ThrowOnError> => (options.client ?? client).get<GetTablesResponses, GetTablesErrors, ThrowOnError>({ url: '/connection/{connection_id}/table', ...options });

/**
 * Get Entity Columns
 *
 * Column types, nullability, defaults, primary key and indexes for a table.
 */
export const getEntityColumns = <ThrowOnError extends boolean = false>(options: Options<GetEntityColumnsData, ThrowOnError>): RequestResult<GetEntityColumnsResponses, GetEntityColumnsErrors, ThrowOnError> => (options.client ?? client).get<GetEntityColumnsResponses, GetEntityColumnsErrors, ThrowOnError>({ url: '/connection/{connection_id}/entities/{entity_name}/columns', ...options });

/**
 * Get Entity Rows
 *
 * Read a page of rows with a stable ordering.
 *
 * When the table has a single-column primary key the page is fetched with a
 * keyset scan (`WHERE pk > after`), which stays correct and fast as the offset
 * grows. Otherwise it falls back to OFFSET and says so in `warnings`.
 */
export const getEntityRows = <ThrowOnError extends boolean = false>(options: Options<GetEntityRowsData, ThrowOnError>): RequestResult<GetEntityRowsResponses, GetEntityRowsErrors, ThrowOnError> => (options.client ?? client).get<GetEntityRowsResponses, GetEntityRowsErrors, ThrowOnError>({ url: '/connection/{connection_id}/entities/{entity_name}/rows', ...options });

/**
 * Execute Query
 *
 * Run an arbitrary query, reporting its risk, timing and column metadata.
 *
 * A connection marked read-only rejects anything that writes unless the caller
 * explicitly passes `allow_writes`.
 */
export const executeQuery = <ThrowOnError extends boolean = false>(options: Options<ExecuteQueryData, ThrowOnError>): RequestResult<ExecuteQueryResponses, ExecuteQueryErrors, ThrowOnError> => (options.client ?? client).get<ExecuteQueryResponses, ExecuteQueryErrors, ThrowOnError>({ url: '/connection/{connection_id}/entities/{entity_name}/queries', ...options });

/**
 * Explain Query
 *
 * Report the plan for a query without executing it.
 *
 * Says whether an index is used, how many rows the planner expects and which
 * speed bucket that falls into.
 */
export const explainQuery = <ThrowOnError extends boolean = false>(options: Options<ExplainQueryData, ThrowOnError>): RequestResult<ExplainQueryResponses, ExplainQueryErrors, ThrowOnError> => (options.client ?? client).get<ExplainQueryResponses, ExplainQueryErrors, ThrowOnError>({ url: '/connection/{connection_id}/entities/{entity_name}/explain', ...options });

/**
 * Get Entity Stats
 *
 * Null share, distinct count and most common values, per column.
 */
export const getEntityStats = <ThrowOnError extends boolean = false>(options: Options<GetEntityStatsData, ThrowOnError>): RequestResult<GetEntityStatsResponses, GetEntityStatsErrors, ThrowOnError> => (options.client ?? client).get<GetEntityStatsResponses, GetEntityStatsErrors, ThrowOnError>({ url: '/connection/{connection_id}/entities/{entity_name}/stats', ...options });

/**
 * Export Entity
 *
 * Export rows as CSV, JSON or NDJSON.
 *
 * Exports what the user is looking at: pass the same `query` the grid ran and
 * a `columns` list to keep only the visible columns, in their displayed order.
 * Values keep their type — timestamps go out as ISO 8601, UUIDs as text, JSON
 * as JSON, binary as base64.
 */
export const exportEntity = <ThrowOnError extends boolean = false>(options: Options<ExportEntityData, ThrowOnError>): RequestResult<ExportEntityResponses, ExportEntityErrors, ThrowOnError> => (options.client ?? client).get<ExportEntityResponses, ExportEntityErrors, ThrowOnError>({ url: '/connection/{connection_id}/entities/{entity_name}/export', ...options });

/**
 * Send Request
 *
 * Send a request from the server and return the whole response.
 *
 * Running server-side is what makes this usable at all: the browser cannot
 * call an arbitrary origin because of CORS, and any credential it sent would
 * be readable by the page.
 */
export const sendRequest = <ThrowOnError extends boolean = false>(options: Options<SendRequestData, ThrowOnError>): RequestResult<SendRequestResponses, SendRequestErrors, ThrowOnError> => (options.client ?? client).post<SendRequestResponses, SendRequestErrors, ThrowOnError>({
    url: '/connection/{connection_id}/request',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List Requests
 */
export const listRequests = <ThrowOnError extends boolean = false>(options: Options<ListRequestsData, ThrowOnError>): RequestResult<ListRequestsResponses, ListRequestsErrors, ThrowOnError> => (options.client ?? client).get<ListRequestsResponses, ListRequestsErrors, ThrowOnError>({ url: '/connection/{connection_id}/requests', ...options });

/**
 * Create Request
 */
export const createRequest = <ThrowOnError extends boolean = false>(options: Options<CreateRequestData, ThrowOnError>): RequestResult<CreateRequestResponses, CreateRequestErrors, ThrowOnError> => (options.client ?? client).post<CreateRequestResponses, CreateRequestErrors, ThrowOnError>({
    url: '/connection/{connection_id}/requests',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Request
 */
export const deleteRequest = <ThrowOnError extends boolean = false>(options: Options<DeleteRequestData, ThrowOnError>): RequestResult<DeleteRequestResponses, DeleteRequestErrors, ThrowOnError> => (options.client ?? client).delete<DeleteRequestResponses, DeleteRequestErrors, ThrowOnError>({ url: '/connection/{connection_id}/requests/{request_uid}', ...options });

/**
 * Get Request
 */
export const getRequest = <ThrowOnError extends boolean = false>(options: Options<GetRequestData, ThrowOnError>): RequestResult<GetRequestResponses, GetRequestErrors, ThrowOnError> => (options.client ?? client).get<GetRequestResponses, GetRequestErrors, ThrowOnError>({ url: '/connection/{connection_id}/requests/{request_uid}', ...options });

/**
 * Update Request
 */
export const updateRequest = <ThrowOnError extends boolean = false>(options: Options<UpdateRequestData, ThrowOnError>): RequestResult<UpdateRequestResponses, UpdateRequestErrors, ThrowOnError> => (options.client ?? client).put<UpdateRequestResponses, UpdateRequestErrors, ThrowOnError>({
    url: '/connection/{connection_id}/requests/{request_uid}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Variables
 *
 * Variables for a connection, with secret-looking values masked.
 */
export const getVariables = <ThrowOnError extends boolean = false>(options: Options<GetVariablesData, ThrowOnError>): RequestResult<GetVariablesResponses, GetVariablesErrors, ThrowOnError> => (options.client ?? client).get<GetVariablesResponses, GetVariablesErrors, ThrowOnError>({ url: '/connection/{connection_id}/variables', ...options });

/**
 * Set Variables
 */
export const setVariables = <ThrowOnError extends boolean = false>(options: Options<SetVariablesData, ThrowOnError>): RequestResult<SetVariablesResponses, SetVariablesErrors, ThrowOnError> => (options.client ?? client).put<SetVariablesResponses, SetVariablesErrors, ThrowOnError>({
    url: '/connection/{connection_id}/variables',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Health
 */
export const health = <ThrowOnError extends boolean = false>(options?: Options<HealthData, ThrowOnError>): RequestResult<HealthResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });
