// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * Body_upload_file
 */
export type BodyUploadFile = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * BucketModel
 */
export type BucketModel = {
    /**
     * Uid
     */
    uid: string;
    /**
     * Filename
     */
    filename: string;
};

/**
 * ConnectionsModel
 */
export type ConnectionsModel = {
    /**
     * Uid
     */
    uid: string;
    /**
     * Name
     */
    name: string;
    /**
     * Connection Uri
     */
    connection_uri: string;
    source: SourceConfig;
};

/**
 * ConnectionsModelList
 */
export type ConnectionsModelList = {
    /**
     * Connections
     */
    connections: Array<ConnectionsModel>;
    /**
     * Total
     */
    total: number;
};

/**
 * CreateConnectionsModel
 */
export type CreateConnectionsModel = {
    source: SourceConfig;
    /**
     * Name
     */
    name: string;
    /**
     * Connection Uri
     */
    connection_uri: string;
};

/**
 * EntityModel
 */
export type EntityModel = {
    /**
     * Name
     */
    name: string;
};

/**
 * EntityModelList
 */
export type EntityModelList = {
    /**
     * Entities
     */
    entities: Array<EntityModel>;
    /**
     * Total
     */
    total: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * QueryResult
 */
export type QueryResult = {
    /**
     * Query
     */
    query: string;
    /**
     * Connection Id
     */
    connection_id: string;
    /**
     * Entity Name
     */
    entity_name: string;
    /**
     * Limit
     */
    limit?: number | null;
    /**
     * Offset
     */
    offset?: number | null;
    /**
     * Rows
     */
    rows: Array<unknown>;
    /**
     * Columns
     */
    columns: Array<unknown>;
};

/**
 * SourceConfig
 */
export type SourceConfig = 'postgres' | 'sqlite' | 'mysql' | 'api';

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type ListConnectionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/connections';
};

export type ListConnectionsResponses = {
    /**
     * Successful Response
     */
    200: ConnectionsModelList;
};

export type ListConnectionsResponse = ListConnectionsResponses[keyof ListConnectionsResponses];

export type CreateConnectionData = {
    body: CreateConnectionsModel;
    path?: never;
    query?: never;
    url: '/connections';
};

export type CreateConnectionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateConnectionError = CreateConnectionErrors[keyof CreateConnectionErrors];

export type CreateConnectionResponses = {
    /**
     * Successful Response
     */
    200: ConnectionsModel;
};

export type CreateConnectionResponse = CreateConnectionResponses[keyof CreateConnectionResponses];

export type GetConnectionData = {
    body?: never;
    path: {
        /**
         * Connection Uid
         */
        connection_uid: string;
    };
    query?: never;
    url: '/connections/{connection_uid}';
};

export type GetConnectionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetConnectionError = GetConnectionErrors[keyof GetConnectionErrors];

export type GetConnectionResponses = {
    /**
     * Successful Response
     */
    200: ConnectionsModel;
};

export type GetConnectionResponse = GetConnectionResponses[keyof GetConnectionResponses];

export type GetEntitiesData = {
    body?: never;
    path: {
        /**
         * Connection Id
         */
        connection_id: string;
    };
    query?: never;
    url: '/connections/{connection_id}/entities';
};

export type GetEntitiesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEntitiesError = GetEntitiesErrors[keyof GetEntitiesErrors];

export type GetEntitiesResponses = {
    /**
     * Successful Response
     */
    200: EntityModelList;
};

export type GetEntitiesResponse = GetEntitiesResponses[keyof GetEntitiesResponses];

export type GetRowsData = {
    body?: never;
    path: {
        /**
         * Connection Id
         */
        connection_id: string;
        /**
         * Entity Name
         */
        entity_name: string;
    };
    query?: never;
    url: '/connection/{connection_id}/entitities/{entity_name}';
};

export type GetRowsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRowsError = GetRowsErrors[keyof GetRowsErrors];

export type GetRowsResponses = {
    /**
     * Successful Response
     */
    200: QueryResult;
};

export type GetRowsResponse = GetRowsResponses[keyof GetRowsResponses];

export type GetEntityData = {
    body?: never;
    path: {
        /**
         * Connection Id
         */
        connection_id: string;
    };
    query?: never;
    url: '/connections/{connection_id}/entities/{entity}';
};

export type GetEntityErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEntityError = GetEntityErrors[keyof GetEntityErrors];

export type GetEntityResponses = {
    /**
     * Successful Response
     */
    200: EntityModelList;
};

export type GetEntityResponse = GetEntityResponses[keyof GetEntityResponses];

export type UploadFileData = {
    body: BodyUploadFile;
    path?: never;
    query?: never;
    url: '/bucket';
};

export type UploadFileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadFileError = UploadFileErrors[keyof UploadFileErrors];

export type UploadFileResponses = {
    /**
     * Successful Response
     */
    200: BucketModel;
};

export type UploadFileResponse = UploadFileResponses[keyof UploadFileResponses];

export type ExecuteQueryData = {
    body?: never;
    path: {
        /**
         * Connection Id
         */
        connection_id: string;
        /**
         * Entity Name
         */
        entity_name: string;
    };
    query?: {
        /**
         * Query
         */
        query?: string;
    };
    url: '/connection/{connection_id}/entitities/{entity_name}/queries';
};

export type ExecuteQueryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExecuteQueryError = ExecuteQueryErrors[keyof ExecuteQueryErrors];

export type ExecuteQueryResponses = {
    /**
     * Successful Response
     */
    200: QueryResult;
};

export type ExecuteQueryResponse = ExecuteQueryResponses[keyof ExecuteQueryResponses];

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type Health2Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type Health2Responses = {
    /**
     * Successful Response
     */
    200: unknown;
};
