// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Body_upload_file
 */
export type BodyUploadFile = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * BucketModel
 */
export type BucketModel = {
    /**
     * Uid
     */
    uid: string;
    /**
     * Filename
     */
    filename: string;
    /**
     * Connection Uri
     */
    connection_uri: string;
    /**
     * Size
     */
    size?: number | null;
};

/**
 * ColumnModel
 */
export type ColumnModel = {
    /**
     * Name
     */
    name: string;
    /**
     * Type
     */
    type?: string | null;
    /**
     * Kind
     */
    kind?: 'uuid' | 'text' | 'number' | 'boolean' | 'timestamp' | 'json' | 'binary';
    /**
     * Nullable
     */
    nullable?: boolean;
    /**
     * Default
     */
    default?: string | null;
    /**
     * Primary Key
     */
    primary_key?: boolean;
    /**
     * Indexed
     */
    indexed?: boolean;
    /**
     * Sensitive
     */
    sensitive?: boolean;
    /**
     * Monospace
     */
    monospace?: boolean;
    /**
     * Position
     */
    position?: number;
};

/**
 * ColumnStatsModel
 */
export type ColumnStatsModel = {
    /**
     * Name
     */
    name: string;
    /**
     * Kind
     */
    kind?: 'uuid' | 'text' | 'number' | 'boolean' | 'timestamp' | 'json' | 'binary';
    /**
     * Null Count
     */
    null_count?: number;
    /**
     * Null Percent
     */
    null_percent?: number;
    /**
     * Distinct Count
     */
    distinct_count?: number | null;
    /**
     * Top Values
     */
    top_values?: Array<ValueCountModel>;
};

/**
 * ConnectionRole
 */
export type ConnectionRole = 'primary' | 'replica';

/**
 * ConnectionStatusModel
 *
 * Result of dialling a connection without running a user query.
 */
export type ConnectionStatusModel = {
    /**
     * Uid
     */
    uid: string;
    /**
     * Reachable
     */
    reachable: boolean;
    /**
     * Detail
     */
    detail?: string | null;
    /**
     * Latency Ms
     */
    latency_ms?: number | null;
    /**
     * Server Version
     */
    server_version?: string | null;
};

/**
 * ConnectionsModel
 */
export type ConnectionsModel = {
    /**
     * Uid
     */
    uid: string;
    /**
     * Name
     */
    name: string;
    /**
     * Connection Uri
     */
    connection_uri: string;
    source: SourceConfig;
    environment?: Environment;
    role?: ConnectionRole;
    /**
     * Read Only
     */
    read_only?: boolean;
    /**
     * Supports Schemas
     */
    supports_schemas?: boolean;
};

/**
 * ConnectionsModelList
 */
export type ConnectionsModelList = {
    /**
     * Connections
     */
    connections: Array<ConnectionsModel>;
    /**
     * Total
     */
    total: number;
};

/**
 * CreateConnectionsModel
 */
export type CreateConnectionsModel = {
    source: SourceConfig;
    /**
     * Name
     */
    name: string;
    /**
     * Connection Uri
     */
    connection_uri: string;
    environment?: Environment;
    role?: ConnectionRole;
    /**
     * Read Only
     */
    read_only?: boolean;
};

/**
 * Environment
 *
 * Where a connection points, so the UI can warn before touching production.
 */
export type Environment = 'local' | 'staging' | 'production';

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * IndexModel
 */
export type IndexModel = {
    /**
     * Name
     */
    name: string;
    /**
     * Columns
     */
    columns: Array<string>;
    /**
     * Unique
     */
    unique?: boolean;
    /**
     * Primary
     */
    primary?: boolean;
};

/**
 * QueryInsightModel
 *
 * What the planner intends to do, without running the query.
 */
export type QueryInsightModel = {
    /**
     * Connection Id
     */
    connection_id: string;
    /**
     * Query
     */
    query: string;
    /**
     * Supported
     */
    supported?: boolean;
    /**
     * Scans
     */
    scans?: Array<ScanModel>;
    /**
     * Estimated Rows
     */
    estimated_rows?: number | null;
    /**
     * Estimated Cost
     */
    estimated_cost?: number | null;
    /**
     * Speed
     */
    speed?: 'fast' | 'medium' | 'slow' | null;
    /**
     * Uses Index
     */
    uses_index?: boolean;
    /**
     * Warnings
     */
    warnings?: Array<string>;
    /**
     * Plan
     */
    plan?: Array<unknown>;
};

/**
 * QueryResult
 */
export type QueryResult = {
    /**
     * Query
     */
    query: string;
    /**
     * Connection Id
     */
    connection_id: string;
    /**
     * Entity Name
     */
    entity_name: string;
    /**
     * Limit
     */
    limit?: number | null;
    /**
     * Offset
     */
    offset?: number | null;
    /**
     * Rows
     */
    rows: Array<unknown>;
    /**
     * Columns
     */
    columns: Array<ColumnModel>;
    /**
     * Row Count
     */
    row_count?: number;
    /**
     * Rows Affected
     */
    rows_affected?: number;
    /**
     * Returns Rows
     */
    returns_rows?: boolean;
    /**
     * Truncated
     */
    truncated?: boolean;
    /**
     * Execution Time Ms
     */
    execution_time_ms?: number;
    risk?: QueryRiskModel;
};

/**
 * QueryRiskModel
 */
export type QueryRiskModel = {
    /**
     * Level
     */
    level?: 'safe' | 'caution' | 'dangerous';
    /**
     * Statement
     */
    statement?: string;
    /**
     * Read Only
     */
    read_only?: boolean;
    /**
     * Statement Count
     */
    statement_count?: number;
    /**
     * Warnings
     */
    warnings?: Array<string>;
};

/**
 * RowPageModel
 *
 * A page of rows fetched through the deterministic pagination endpoint.
 */
export type RowPageModel = {
    /**
     * Connection Id
     */
    connection_id: string;
    /**
     * Entity Name
     */
    entity_name: string;
    /**
     * Schema Name
     */
    schema_name?: string | null;
    /**
     * Rows
     */
    rows: Array<unknown>;
    /**
     * Columns
     */
    columns: Array<ColumnModel>;
    /**
     * Row Count
     */
    row_count: number;
    /**
     * Total Rows
     */
    total_rows?: number | null;
    /**
     * Limit
     */
    limit: number;
    /**
     * Offset
     */
    offset?: number | null;
    /**
     * Next Cursor
     */
    next_cursor?: string | null;
    /**
     * Cursor Column
     */
    cursor_column?: string | null;
    /**
     * Keyset
     */
    keyset?: boolean;
    /**
     * Query
     */
    query: string;
    /**
     * Execution Time Ms
     */
    execution_time_ms?: number;
    /**
     * Warnings
     */
    warnings?: Array<string>;
};

/**
 * ScanModel
 */
export type ScanModel = {
    /**
     * Table
     */
    table?: string | null;
    /**
     * Type
     */
    type: string;
    /**
     * Index
     */
    index?: string | null;
    /**
     * Detail
     */
    detail?: string;
    /**
     * Estimated Rows
     */
    estimated_rows?: number | null;
};

/**
 * SchemaModel
 */
export type SchemaModel = {
    /**
     * Name
     */
    name: string;
};

/**
 * SchemaModelList
 */
export type SchemaModelList = {
    /**
     * Schemas
     */
    schemas: Array<SchemaModel>;
    /**
     * Total
     */
    total: number;
};

/**
 * SourceConfig
 */
export type SourceConfig = 'postgres' | 'sqlite' | 'mysql' | 'api';

/**
 * TableModel
 */
export type TableModel = {
    /**
     * Name
     */
    name: string;
};

/**
 * TableModelList
 */
export type TableModelList = {
    /**
     * Tables
     */
    tables: Array<TableModel>;
    /**
     * Total
     */
    total: number;
};

/**
 * TableSchemaModel
 */
export type TableSchemaModel = {
    /**
     * Connection Id
     */
    connection_id: string;
    /**
     * Entity Name
     */
    entity_name: string;
    /**
     * Schema Name
     */
    schema_name?: string | null;
    /**
     * Columns
     */
    columns: Array<ColumnModel>;
    /**
     * Indexes
     */
    indexes: Array<IndexModel>;
    /**
     * Primary Key
     */
    primary_key: Array<string>;
    /**
     * Row Count
     */
    row_count?: number | null;
    /**
     * Total
     */
    total: number;
};

/**
 * TableStatsModel
 */
export type TableStatsModel = {
    /**
     * Connection Id
     */
    connection_id: string;
    /**
     * Entity Name
     */
    entity_name: string;
    /**
     * Schema Name
     */
    schema_name?: string | null;
    /**
     * Row Count
     */
    row_count?: number;
    /**
     * Scanned Rows
     */
    scanned_rows?: number;
    /**
     * Sampled
     */
    sampled?: boolean;
    /**
     * Columns
     */
    columns?: Array<ColumnStatsModel>;
    /**
     * Execution Time Ms
     */
    execution_time_ms?: number;
};

/**
 * UpdateConnectionsModel
 */
export type UpdateConnectionsModel = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Connection Uri
     */
    connection_uri?: string | null;
    source?: SourceConfig | null;
    environment?: Environment | null;
    role?: ConnectionRole | null;
    /**
     * Read Only
     */
    read_only?: boolean | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * ValueCountModel
 */
export type ValueCountModel = {
    /**
     * Value
     */
    value?: unknown;
    /**
     * Count
     */
    count: number;
};

export type ListConnectionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/connections';
};

export type ListConnectionsResponses = {
    /**
     * Successful Response
     */
    200: ConnectionsModelList;
};

export type ListConnectionsResponse = ListConnectionsResponses[keyof ListConnectionsResponses];

export type CreateConnectionData = {
    body: CreateConnectionsModel;
    path?: never;
    query?: never;
    url: '/connections';
};

export type CreateConnectionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateConnectionError = CreateConnectionErrors[keyof CreateConnectionErrors];

export type CreateConnectionResponses = {
    /**
     * Successful Response
     */
    200: ConnectionsModel;
};

export type CreateConnectionResponse = CreateConnectionResponses[keyof CreateConnectionResponses];

export type DeleteConnectionData = {
    body?: never;
    path: {
        /**
         * Connection Uid
         */
        connection_uid: string;
    };
    query?: never;
    url: '/connections/{connection_uid}';
};

export type DeleteConnectionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteConnectionError = DeleteConnectionErrors[keyof DeleteConnectionErrors];

export type DeleteConnectionResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteConnectionResponse = DeleteConnectionResponses[keyof DeleteConnectionResponses];

export type GetConnectionData = {
    body?: never;
    path: {
        /**
         * Connection Uid
         */
        connection_uid: string;
    };
    query?: never;
    url: '/connections/{connection_uid}';
};

export type GetConnectionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetConnectionError = GetConnectionErrors[keyof GetConnectionErrors];

export type GetConnectionResponses = {
    /**
     * Successful Response
     */
    200: ConnectionsModel;
};

export type GetConnectionResponse = GetConnectionResponses[keyof GetConnectionResponses];

export type UpdateConnectionData = {
    body: UpdateConnectionsModel;
    path: {
        /**
         * Connection Uid
         */
        connection_uid: string;
    };
    query?: never;
    url: '/connections/{connection_uid}';
};

export type UpdateConnectionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateConnectionError = UpdateConnectionErrors[keyof UpdateConnectionErrors];

export type UpdateConnectionResponses = {
    /**
     * Successful Response
     */
    200: ConnectionsModel;
};

export type UpdateConnectionResponse = UpdateConnectionResponses[keyof UpdateConnectionResponses];

export type GetConnectionStatusData = {
    body?: never;
    path: {
        /**
         * Connection Uid
         */
        connection_uid: string;
    };
    query?: never;
    url: '/connections/{connection_uid}/status';
};

export type GetConnectionStatusErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetConnectionStatusError = GetConnectionStatusErrors[keyof GetConnectionStatusErrors];

export type GetConnectionStatusResponses = {
    /**
     * Successful Response
     */
    200: ConnectionStatusModel;
};

export type GetConnectionStatusResponse = GetConnectionStatusResponses[keyof GetConnectionStatusResponses];

export type UploadFileData = {
    body: BodyUploadFile;
    path?: never;
    query?: never;
    url: '/bucket';
};

export type UploadFileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadFileError = UploadFileErrors[keyof UploadFileErrors];

export type UploadFileResponses = {
    /**
     * Successful Response
     */
    200: BucketModel;
};

export type UploadFileResponse = UploadFileResponses[keyof UploadFileResponses];

export type GetSchemasData = {
    body?: never;
    path: {
        /**
         * Connection Id
         */
        connection_id: string;
    };
    query?: never;
    url: '/connection/{connection_id}/schema';
};

export type GetSchemasErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSchemasError = GetSchemasErrors[keyof GetSchemasErrors];

export type GetSchemasResponses = {
    /**
     * Successful Response
     */
    200: SchemaModelList;
};

export type GetSchemasResponse = GetSchemasResponses[keyof GetSchemasResponses];

export type GetTablesData = {
    body?: never;
    path: {
        /**
         * Connection Id
         */
        connection_id: string;
    };
    query?: {
        /**
         * Schema
         */
        schema?: string | null;
    };
    url: '/connection/{connection_id}/table';
};

export type GetTablesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTablesError = GetTablesErrors[keyof GetTablesErrors];

export type GetTablesResponses = {
    /**
     * Successful Response
     */
    200: TableModelList;
};

export type GetTablesResponse = GetTablesResponses[keyof GetTablesResponses];

export type GetEntityColumnsData = {
    body?: never;
    path: {
        /**
         * Connection Id
         */
        connection_id: string;
        /**
         * Entity Name
         */
        entity_name: string;
    };
    query?: {
        /**
         * Schema
         */
        schema?: string | null;
        /**
         * Include Row Count
         */
        include_row_count?: boolean;
    };
    url: '/connection/{connection_id}/entities/{entity_name}/columns';
};

export type GetEntityColumnsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEntityColumnsError = GetEntityColumnsErrors[keyof GetEntityColumnsErrors];

export type GetEntityColumnsResponses = {
    /**
     * Successful Response
     */
    200: TableSchemaModel;
};

export type GetEntityColumnsResponse = GetEntityColumnsResponses[keyof GetEntityColumnsResponses];

export type GetEntityRowsData = {
    body?: never;
    path: {
        /**
         * Connection Id
         */
        connection_id: string;
        /**
         * Entity Name
         */
        entity_name: string;
    };
    query?: {
        /**
         * Schema
         */
        schema?: string | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number | null;
        /**
         * After
         */
        after?: string | null;
        /**
         * Order By
         */
        order_by?: string | null;
    };
    url: '/connection/{connection_id}/entities/{entity_name}/rows';
};

export type GetEntityRowsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEntityRowsError = GetEntityRowsErrors[keyof GetEntityRowsErrors];

export type GetEntityRowsResponses = {
    /**
     * Successful Response
     */
    200: RowPageModel;
};

export type GetEntityRowsResponse = GetEntityRowsResponses[keyof GetEntityRowsResponses];

export type ExecuteQueryData = {
    body?: never;
    path: {
        /**
         * Connection Id
         */
        connection_id: string;
        /**
         * Entity Name
         */
        entity_name: string;
    };
    query: {
        /**
         * Query
         */
        query: string;
        /**
         * Limit
         */
        limit?: number | null;
        /**
         * Offset
         */
        offset?: number | null;
        /**
         * Schema
         */
        schema?: string | null;
        /**
         * Allow Writes
         */
        allow_writes?: boolean;
    };
    url: '/connection/{connection_id}/entities/{entity_name}/queries';
};

export type ExecuteQueryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExecuteQueryError = ExecuteQueryErrors[keyof ExecuteQueryErrors];

export type ExecuteQueryResponses = {
    /**
     * Successful Response
     */
    200: QueryResult;
};

export type ExecuteQueryResponse = ExecuteQueryResponses[keyof ExecuteQueryResponses];

export type ExplainQueryData = {
    body?: never;
    path: {
        /**
         * Connection Id
         */
        connection_id: string;
        /**
         * Entity Name
         */
        entity_name: string;
    };
    query: {
        /**
         * Query
         */
        query: string;
    };
    url: '/connection/{connection_id}/entities/{entity_name}/explain';
};

export type ExplainQueryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExplainQueryError = ExplainQueryErrors[keyof ExplainQueryErrors];

export type ExplainQueryResponses = {
    /**
     * Successful Response
     */
    200: QueryInsightModel;
};

export type ExplainQueryResponse = ExplainQueryResponses[keyof ExplainQueryResponses];

export type GetEntityStatsData = {
    body?: never;
    path: {
        /**
         * Connection Id
         */
        connection_id: string;
        /**
         * Entity Name
         */
        entity_name: string;
    };
    query?: {
        /**
         * Schema
         */
        schema?: string | null;
        /**
         * Top Values
         */
        top_values?: boolean;
        /**
         * Sample
         */
        sample?: number;
    };
    url: '/connection/{connection_id}/entities/{entity_name}/stats';
};

export type GetEntityStatsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEntityStatsError = GetEntityStatsErrors[keyof GetEntityStatsErrors];

export type GetEntityStatsResponses = {
    /**
     * Successful Response
     */
    200: TableStatsModel;
};

export type GetEntityStatsResponse = GetEntityStatsResponses[keyof GetEntityStatsResponses];

export type ExportEntityData = {
    body?: never;
    path: {
        /**
         * Connection Id
         */
        connection_id: string;
        /**
         * Entity Name
         */
        entity_name: string;
    };
    query?: {
        /**
         * Schema
         */
        schema?: string | null;
        /**
         * Query
         */
        query?: string | null;
        /**
         * Columns
         */
        columns?: string | null;
        /**
         * Format
         */
        format?: string;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/connection/{connection_id}/entities/{entity_name}/export';
};

export type ExportEntityErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExportEntityError = ExportEntityErrors[keyof ExportEntityErrors];

export type ExportEntityResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
