// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AppwriteJWTRequest
 *
 * Provision a broker credential from an Appwrite project.
 *
 * Appwrite's MQTT push broker authenticates a client against a real session
 * or JWT, so testing it needs one. Given the project and an API key with the
 * users scope, the server mints a throwaway user's JWT - the credential the
 * broker accepts - so the person does not have to leave DataPilot to sign in.
 */
export type AppwriteJwtRequest = {
    /**
     * Endpoint
     */
    endpoint: string;
    /**
     * Project
     */
    project: string;
    /**
     * Api Key
     */
    api_key: string;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * AppwriteJWTResult
 */
export type AppwriteJwtResult = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Jwt
     */
    jwt: string;
    /**
     * Project
     */
    project: string;
};

/**
 * AuthModel
 */
export type AuthModel = {
    /**
     * Type
     */
    type?: 'none' | 'bearer' | 'basic' | 'header';
    /**
     * Token
     */
    token?: string | null;
    /**
     * Username
     */
    username?: string | null;
    /**
     * Password
     */
    password?: string | null;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Value
     */
    value?: string | null;
};

/**
 * Body_upload_file
 */
export type BodyUploadFile = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * BucketModel
 */
export type BucketModel = {
    /**
     * Uid
     */
    uid: string;
    /**
     * Filename
     */
    filename: string;
    /**
     * Connection Uri
     */
    connection_uri: string;
    /**
     * Size
     */
    size?: number | null;
};

/**
 * ColumnModel
 */
export type ColumnModel = {
    /**
     * Name
     */
    name: string;
    /**
     * Type
     */
    type?: string | null;
    /**
     * Kind
     */
    kind?: 'uuid' | 'text' | 'number' | 'boolean' | 'timestamp' | 'json' | 'binary';
    /**
     * Nullable
     */
    nullable?: boolean;
    /**
     * Default
     */
    default?: string | null;
    /**
     * Primary Key
     */
    primary_key?: boolean;
    /**
     * Indexed
     */
    indexed?: boolean;
    /**
     * Sensitive
     */
    sensitive?: boolean;
    /**
     * Monospace
     */
    monospace?: boolean;
    /**
     * Position
     */
    position?: number;
};

/**
 * ColumnStatsModel
 */
export type ColumnStatsModel = {
    /**
     * Name
     */
    name: string;
    /**
     * Kind
     */
    kind?: 'uuid' | 'text' | 'number' | 'boolean' | 'timestamp' | 'json' | 'binary';
    /**
     * Null Count
     */
    null_count?: number;
    /**
     * Null Percent
     */
    null_percent?: number;
    /**
     * Distinct Count
     */
    distinct_count?: number | null;
    /**
     * Top Values
     */
    top_values?: Array<ValueCountModel>;
};

/**
 * ConnectionProbeModel
 */
export type ConnectionProbeModel = {
    /**
     * Reachable
     */
    reachable: boolean;
    /**
     * Detail
     */
    detail?: string | null;
    /**
     * Latency Ms
     */
    latency_ms?: number | null;
    /**
     * Server Version
     */
    server_version?: string | null;
};

/**
 * ConnectionRole
 */
export type ConnectionRole = 'primary' | 'replica';

/**
 * ConnectionStatusModel
 *
 * Result of dialling a connection without running a user query.
 */
export type ConnectionStatusModel = {
    /**
     * Uid
     */
    uid: string;
    /**
     * Reachable
     */
    reachable: boolean;
    /**
     * Detail
     */
    detail?: string | null;
    /**
     * Latency Ms
     */
    latency_ms?: number | null;
    /**
     * Server Version
     */
    server_version?: string | null;
};

/**
 * ConnectionsModel
 */
export type ConnectionsModel = {
    /**
     * Uid
     */
    uid: string;
    /**
     * Name
     */
    name: string;
    /**
     * Connection Uri
     */
    connection_uri: string;
    source: SourceConfig;
    environment?: Environment;
    role?: ConnectionRole;
    /**
     * Read Only
     */
    read_only?: boolean;
    /**
     * Supports Schemas
     */
    supports_schemas?: boolean;
};

/**
 * ConnectionsModelList
 */
export type ConnectionsModelList = {
    /**
     * Connections
     */
    connections: Array<ConnectionsModel>;
    /**
     * Total
     */
    total: number;
};

/**
 * CreateConnectionsModel
 */
export type CreateConnectionsModel = {
    source: SourceConfig;
    /**
     * Name
     */
    name: string;
    /**
     * Connection Uri
     */
    connection_uri: string;
    environment?: Environment;
    role?: ConnectionRole;
    /**
     * Read Only
     */
    read_only?: boolean;
};

/**
 * Environment
 *
 * Where a connection points, so the UI can warn before touching production.
 */
export type Environment = 'local' | 'staging' | 'production';

/**
 * FlowListModel
 */
export type FlowListModel = {
    /**
     * Flows
     */
    flows?: Array<FlowModel>;
    /**
     * Total
     */
    total?: number;
};

/**
 * FlowModel
 */
export type FlowModel = {
    /**
     * Uid
     */
    uid: string;
    /**
     * Name
     */
    name: string;
    /**
     * Graph
     */
    graph?: {
        [key: string]: unknown;
    };
};

/**
 * FlowSpecModel
 *
 * A node graph as it was drawn.
 */
export type FlowSpecModel = {
    /**
     * Name
     */
    name?: string;
    /**
     * Graph
     */
    graph?: {
        [key: string]: unknown;
    };
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * IndexModel
 */
export type IndexModel = {
    /**
     * Name
     */
    name: string;
    /**
     * Columns
     */
    columns: Array<string>;
    /**
     * Unique
     */
    unique?: boolean;
    /**
     * Primary
     */
    primary?: boolean;
};

/**
 * KeyValueModel
 */
export type KeyValueModel = {
    /**
     * Key
     */
    key: string;
    /**
     * Value
     */
    value?: string;
    /**
     * Enabled
     */
    enabled?: boolean;
};

/**
 * NodeReferenceGroupModel
 *
 * The references one upstream node offers.
 */
export type NodeReferenceGroupModel = {
    /**
     * Node
     */
    node: string;
    /**
     * Kind
     */
    kind: string;
    /**
     * References
     */
    references?: Array<NodeReferenceModel>;
};

/**
 * NodeReferenceModel
 *
 * A `{{...}}` someone can copy, and what it holds right now.
 */
export type NodeReferenceModel = {
    /**
     * Reference
     */
    reference: string;
    /**
     * Value
     */
    value?: string;
};

/**
 * NodeRunModel
 *
 * One node's outcome, the same shape the live run reports.
 */
export type NodeRunModel = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Kind
     */
    kind: string;
    /**
     * State
     */
    state: string;
    /**
     * Elapsed Ms
     */
    elapsed_ms?: number | null;
    /**
     * Summary
     */
    summary?: string;
    /**
     * Result
     */
    result?: unknown;
    /**
     * Error
     */
    error?: string;
    /**
     * Warnings
     */
    warnings?: Array<string>;
    /**
     * Blocked By
     */
    blocked_by?: Array<string>;
};

/**
 * NodeTestModel
 *
 * Testing one node: what it produced, and what it was actually sent.
 */
export type NodeTestModel = {
    node: NodeRunModel;
    /**
     * Resolved Query
     */
    resolved_query?: string;
    /**
     * Resolved Request
     */
    resolved_request?: {
        [key: string]: unknown;
    } | null;
    /**
     * Upstream
     */
    upstream?: Array<NodeRunModel>;
    /**
     * Available
     */
    available?: Array<NodeReferenceGroupModel>;
    /**
     * Offers
     */
    offers?: Array<NodeReferenceModel>;
};

/**
 * QueryInsightModel
 *
 * What the planner intends to do, without running the query.
 */
export type QueryInsightModel = {
    /**
     * Connection Id
     */
    connection_id: string;
    /**
     * Query
     */
    query: string;
    /**
     * Supported
     */
    supported?: boolean;
    /**
     * Scans
     */
    scans?: Array<ScanModel>;
    /**
     * Estimated Rows
     */
    estimated_rows?: number | null;
    /**
     * Estimated Cost
     */
    estimated_cost?: number | null;
    /**
     * Speed
     */
    speed?: 'fast' | 'medium' | 'slow' | null;
    /**
     * Uses Index
     */
    uses_index?: boolean;
    /**
     * Warnings
     */
    warnings?: Array<string>;
    /**
     * Plan
     */
    plan?: Array<unknown>;
    /**
     * Plan Text
     */
    plan_text?: string;
};

/**
 * QueryResult
 */
export type QueryResult = {
    /**
     * Query
     */
    query: string;
    /**
     * Connection Id
     */
    connection_id: string;
    /**
     * Entity Name
     */
    entity_name: string;
    /**
     * Limit
     */
    limit?: number | null;
    /**
     * Offset
     */
    offset?: number | null;
    /**
     * Rows
     */
    rows: Array<unknown>;
    /**
     * Columns
     */
    columns: Array<ColumnModel>;
    /**
     * Row Count
     */
    row_count?: number;
    /**
     * Rows Affected
     */
    rows_affected?: number;
    /**
     * Returns Rows
     */
    returns_rows?: boolean;
    /**
     * Truncated
     */
    truncated?: boolean;
    /**
     * Execution Time Ms
     */
    execution_time_ms?: number;
    risk?: QueryRiskModel;
};

/**
 * QueryRiskModel
 */
export type QueryRiskModel = {
    /**
     * Level
     */
    level?: 'safe' | 'caution' | 'dangerous';
    /**
     * Statement
     */
    statement?: string;
    /**
     * Read Only
     */
    read_only?: boolean;
    /**
     * Statement Count
     */
    statement_count?: number;
    /**
     * Warnings
     */
    warnings?: Array<string>;
};

/**
 * RedisChannelListModel
 */
export type RedisChannelListModel = {
    /**
     * Connection Id
     */
    connection_id: string;
    /**
     * Channels
     */
    channels?: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Pattern Subscriptions
     */
    pattern_subscriptions?: number;
};

/**
 * RedisInfoModel
 */
export type RedisInfoModel = {
    /**
     * Connection Id
     */
    connection_id: string;
    /**
     * Server
     */
    server: string;
    /**
     * Fields
     */
    fields?: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Keyspace
     */
    keyspace?: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Hit Rate
     */
    hit_rate?: number | null;
    /**
     * Pattern Subscriptions
     */
    pattern_subscriptions?: number;
};

/**
 * RedisKeyListModel
 */
export type RedisKeyListModel = {
    /**
     * Connection Id
     */
    connection_id: string;
    /**
     * Pattern
     */
    pattern?: string;
    /**
     * Keys
     */
    keys?: Array<RedisKeyModel>;
    /**
     * Cursor
     */
    cursor?: number;
    /**
     * Complete
     */
    complete?: boolean;
};

/**
 * RedisKeyModel
 */
export type RedisKeyModel = {
    /**
     * Key
     */
    key: string;
    /**
     * Type
     */
    type: string;
    /**
     * Label
     */
    label: string;
    /**
     * Ttl
     */
    ttl?: number | null;
    /**
     * Size
     */
    size?: number | null;
};

/**
 * RedisKeyValueModel
 *
 * One key's contents. Which fields are filled depends on its type.
 */
export type RedisKeyValueModel = {
    /**
     * Connection Id
     */
    connection_id: string;
    /**
     * Key
     */
    key: string;
    /**
     * Type
     */
    type: string;
    /**
     * Label
     */
    label: string;
    /**
     * Ttl
     */
    ttl?: number | null;
    /**
     * Size
     */
    size?: number | null;
    /**
     * Encoding
     */
    encoding?: string | null;
    /**
     * Value
     */
    value?: string | null;
    /**
     * Is Text
     */
    is_text?: boolean;
    /**
     * Entries
     */
    entries?: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Members
     */
    members?: Array<string>;
    /**
     * Truncated
     */
    truncated?: boolean;
};

/**
 * RedisPublishResultModel
 */
export type RedisPublishResultModel = {
    /**
     * Connection Id
     */
    connection_id: string;
    /**
     * Channel
     */
    channel: string;
    /**
     * Received By
     */
    received_by?: number;
};

/**
 * RequestResultModel
 */
export type RequestResultModel = {
    /**
     * Connection Id
     */
    connection_id: string;
    request: SentRequestModel;
    response: ResponseModel;
};

/**
 * RequestSpecModel
 *
 * What to send. A saved request stores exactly this.
 */
export type RequestSpecModel = {
    /**
     * Name
     */
    name?: string;
    /**
     * Method
     */
    method?: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'HEAD' | 'OPTIONS';
    /**
     * Path
     */
    path?: string;
    /**
     * Params
     */
    params?: Array<KeyValueModel>;
    /**
     * Headers
     */
    headers?: Array<KeyValueModel>;
    /**
     * Body Type
     */
    body_type?: 'none' | 'json' | 'form' | 'text';
    /**
     * Body
     */
    body?: unknown;
    auth?: AuthModel | null;
    /**
     * Timeout
     */
    timeout?: number;
    /**
     * Follow Redirects
     */
    follow_redirects?: boolean;
    /**
     * Verify Tls
     */
    verify_tls?: boolean;
};

/**
 * ResponseModel
 */
export type ResponseModel = {
    /**
     * Status
     */
    status: number;
    /**
     * Reason
     */
    reason?: string;
    /**
     * Headers
     */
    headers?: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Body
     */
    body?: string;
    /**
     * Is Text
     */
    is_text?: boolean;
    /**
     * Size
     */
    size?: number;
    /**
     * Truncated
     */
    truncated?: boolean;
    /**
     * Elapsed Ms
     */
    elapsed_ms?: number;
    /**
     * Content Type
     */
    content_type?: string | null;
};

/**
 * RowPageModel
 *
 * A page of rows fetched through the deterministic pagination endpoint.
 */
export type RowPageModel = {
    /**
     * Connection Id
     */
    connection_id: string;
    /**
     * Entity Name
     */
    entity_name: string;
    /**
     * Schema Name
     */
    schema_name?: string | null;
    /**
     * Rows
     */
    rows: Array<unknown>;
    /**
     * Columns
     */
    columns: Array<ColumnModel>;
    /**
     * Row Count
     */
    row_count: number;
    /**
     * Total Rows
     */
    total_rows?: number | null;
    /**
     * Limit
     */
    limit: number;
    /**
     * Offset
     */
    offset?: number | null;
    /**
     * Next Cursor
     */
    next_cursor?: string | null;
    /**
     * Cursor Column
     */
    cursor_column?: string | null;
    /**
     * Keyset
     */
    keyset?: boolean;
    /**
     * Query
     */
    query: string;
    /**
     * Execution Time Ms
     */
    execution_time_ms?: number;
    /**
     * Warnings
     */
    warnings?: Array<string>;
};

/**
 * SavedRequestListModel
 */
export type SavedRequestListModel = {
    /**
     * Requests
     */
    requests: Array<SavedRequestModel>;
    /**
     * Total
     */
    total: number;
};

/**
 * SavedRequestModel
 */
export type SavedRequestModel = {
    /**
     * Name
     */
    name?: string;
    /**
     * Method
     */
    method?: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'HEAD' | 'OPTIONS';
    /**
     * Path
     */
    path?: string;
    /**
     * Params
     */
    params?: Array<KeyValueModel>;
    /**
     * Headers
     */
    headers?: Array<KeyValueModel>;
    /**
     * Body Type
     */
    body_type?: 'none' | 'json' | 'form' | 'text';
    /**
     * Body
     */
    body?: unknown;
    auth?: AuthModel | null;
    /**
     * Timeout
     */
    timeout?: number;
    /**
     * Follow Redirects
     */
    follow_redirects?: boolean;
    /**
     * Verify Tls
     */
    verify_tls?: boolean;
    /**
     * Uid
     */
    uid: string;
    /**
     * Connection Id
     */
    connection_id: string;
    /**
     * Position
     */
    position?: number;
};

/**
 * ScanModel
 */
export type ScanModel = {
    /**
     * Table
     */
    table?: string | null;
    /**
     * Type
     */
    type: string;
    /**
     * Index
     */
    index?: string | null;
    /**
     * Detail
     */
    detail?: string;
    /**
     * Estimated Rows
     */
    estimated_rows?: number | null;
};

/**
 * SchemaModel
 */
export type SchemaModel = {
    /**
     * Name
     */
    name: string;
};

/**
 * SchemaModelList
 */
export type SchemaModelList = {
    /**
     * Schemas
     */
    schemas: Array<SchemaModel>;
    /**
     * Total
     */
    total: number;
};

/**
 * SentRequestModel
 */
export type SentRequestModel = {
    /**
     * Method
     */
    method: string;
    /**
     * Url
     */
    url: string;
    /**
     * Headers
     */
    headers?: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Body
     */
    body?: string | null;
};

/**
 * SlowQueryModel
 *
 * One statement the server itself recorded, whatever backend it came from.
 */
export type SlowQueryModel = {
    /**
     * Digest
     */
    digest: string;
    /**
     * Statement
     */
    statement: string;
    /**
     * Calls
     */
    calls?: number;
    /**
     * Total Ms
     */
    total_ms?: number;
    /**
     * Mean Ms
     */
    mean_ms?: number;
    /**
     * Max Ms
     */
    max_ms?: number | null;
    /**
     * Rows
     */
    rows?: number;
    /**
     * Rows Per Call
     */
    rows_per_call?: number;
    /**
     * Rows Examined
     */
    rows_examined?: number | null;
    /**
     * First Seen
     */
    first_seen?: string | null;
    /**
     * Last Seen
     */
    last_seen?: string | null;
};

/**
 * SlowQueryReportModel
 */
export type SlowQueryReportModel = {
    /**
     * Connection Id
     */
    connection_id: string;
    /**
     * Source
     */
    source: string;
    /**
     * Available
     */
    available?: boolean;
    /**
     * Queries
     */
    queries?: Array<SlowQueryModel>;
    /**
     * Detail
     */
    detail?: string;
    /**
     * Origin
     */
    origin?: string;
};

/**
 * SnapshotComparisonModel
 *
 * What happened between two readings, as the difference in each counter.
 */
export type SnapshotComparisonModel = {
    /**
     * Connection Id
     */
    connection_id: string;
    before: SnapshotModel;
    after: SnapshotModel;
    /**
     * Queries
     */
    queries?: Array<SlowQueryModel>;
};

/**
 * SnapshotDetailModel
 */
export type SnapshotDetailModel = {
    snapshot: SnapshotModel;
    /**
     * Queries
     */
    queries?: Array<SlowQueryModel>;
};

/**
 * SnapshotListModel
 */
export type SnapshotListModel = {
    /**
     * Snapshots
     */
    snapshots?: Array<SnapshotModel>;
    /**
     * Total
     */
    total?: number;
};

/**
 * SnapshotModel
 *
 * A stored reading, so a comparison survives the counters being reset.
 */
export type SnapshotModel = {
    /**
     * Uid
     */
    uid: string;
    /**
     * Connection Id
     */
    connection_id: string;
    /**
     * Taken At
     */
    taken_at: string;
    /**
     * Source
     */
    source: string;
    /**
     * Query Count
     */
    query_count?: number;
    /**
     * Total Ms
     */
    total_ms?: number;
    /**
     * Note
     */
    note?: string;
};

/**
 * SourceConfig
 */
export type SourceConfig = 'postgres' | 'sqlite' | 'mysql' | 'api' | 'redis';

/**
 * TableModel
 */
export type TableModel = {
    /**
     * Name
     */
    name: string;
};

/**
 * TableModelList
 */
export type TableModelList = {
    /**
     * Tables
     */
    tables: Array<TableModel>;
    /**
     * Total
     */
    total: number;
};

/**
 * TableSchemaModel
 */
export type TableSchemaModel = {
    /**
     * Connection Id
     */
    connection_id: string;
    /**
     * Entity Name
     */
    entity_name: string;
    /**
     * Schema Name
     */
    schema_name?: string | null;
    /**
     * Columns
     */
    columns: Array<ColumnModel>;
    /**
     * Indexes
     */
    indexes: Array<IndexModel>;
    /**
     * Primary Key
     */
    primary_key: Array<string>;
    /**
     * Row Count
     */
    row_count?: number | null;
    /**
     * Total
     */
    total: number;
};

/**
 * TableStatsModel
 */
export type TableStatsModel = {
    /**
     * Connection Id
     */
    connection_id: string;
    /**
     * Entity Name
     */
    entity_name: string;
    /**
     * Schema Name
     */
    schema_name?: string | null;
    /**
     * Row Count
     */
    row_count?: number;
    /**
     * Scanned Rows
     */
    scanned_rows?: number;
    /**
     * Sampled
     */
    sampled?: boolean;
    /**
     * Columns
     */
    columns?: Array<ColumnStatsModel>;
    /**
     * Execution Time Ms
     */
    execution_time_ms?: number;
};

/**
 * TestConnectionModel
 *
 * Enough to dial a connection that has not been saved yet.
 */
export type TestConnectionModel = {
    source: SourceConfig;
    /**
     * Connection Uri
     */
    connection_uri: string;
    /**
     * Variables
     */
    variables?: {
        [key: string]: unknown;
    } | null;
};

/**
 * UpdateConnectionsModel
 */
export type UpdateConnectionsModel = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Connection Uri
     */
    connection_uri?: string | null;
    source?: SourceConfig | null;
    environment?: Environment | null;
    role?: ConnectionRole | null;
    /**
     * Read Only
     */
    read_only?: boolean | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * ValueCountModel
 */
export type ValueCountModel = {
    /**
     * Value
     */
    value?: unknown;
    /**
     * Count
     */
    count: number;
};

/**
 * VariablesModel
 */
export type VariablesModel = {
    /**
     * Variables
     */
    variables?: {
        [key: string]: string;
    };
    /**
     * Secret
     */
    secret?: Array<string>;
};

export type TestConnectionData = {
    body: TestConnectionModel;
    path?: never;
    query?: never;
    url: '/connections/test';
};

export type TestConnectionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TestConnectionError = TestConnectionErrors[keyof TestConnectionErrors];

export type TestConnectionResponses = {
    /**
     * Successful Response
     */
    200: ConnectionProbeModel;
};

export type TestConnectionResponse = TestConnectionResponses[keyof TestConnectionResponses];

export type ProvisionAppwriteJwtData = {
    body: AppwriteJwtRequest;
    path?: never;
    query?: never;
    url: '/connections/appwrite/jwt';
};

export type ProvisionAppwriteJwtErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProvisionAppwriteJwtError = ProvisionAppwriteJwtErrors[keyof ProvisionAppwriteJwtErrors];

export type ProvisionAppwriteJwtResponses = {
    /**
     * Successful Response
     */
    200: AppwriteJwtResult;
};

export type ProvisionAppwriteJwtResponse = ProvisionAppwriteJwtResponses[keyof ProvisionAppwriteJwtResponses];

export type ListConnectionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/connections';
};

export type ListConnectionsResponses = {
    /**
     * Successful Response
     */
    200: ConnectionsModelList;
};

export type ListConnectionsResponse = ListConnectionsResponses[keyof ListConnectionsResponses];

export type CreateConnectionData = {
    body: CreateConnectionsModel;
    path?: never;
    query?: never;
    url: '/connections';
};

export type CreateConnectionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateConnectionError = CreateConnectionErrors[keyof CreateConnectionErrors];

export type CreateConnectionResponses = {
    /**
     * Successful Response
     */
    200: ConnectionsModel;
};

export type CreateConnectionResponse = CreateConnectionResponses[keyof CreateConnectionResponses];

export type DeleteConnectionData = {
    body?: never;
    path: {
        /**
         * Connection Uid
         */
        connection_uid: string;
    };
    query?: never;
    url: '/connections/{connection_uid}';
};

export type DeleteConnectionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteConnectionError = DeleteConnectionErrors[keyof DeleteConnectionErrors];

export type DeleteConnectionResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteConnectionResponse = DeleteConnectionResponses[keyof DeleteConnectionResponses];

export type GetConnectionData = {
    body?: never;
    path: {
        /**
         * Connection Uid
         */
        connection_uid: string;
    };
    query?: never;
    url: '/connections/{connection_uid}';
};

export type GetConnectionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetConnectionError = GetConnectionErrors[keyof GetConnectionErrors];

export type GetConnectionResponses = {
    /**
     * Successful Response
     */
    200: ConnectionsModel;
};

export type GetConnectionResponse = GetConnectionResponses[keyof GetConnectionResponses];

export type UpdateConnectionData = {
    body: UpdateConnectionsModel;
    path: {
        /**
         * Connection Uid
         */
        connection_uid: string;
    };
    query?: never;
    url: '/connections/{connection_uid}';
};

export type UpdateConnectionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateConnectionError = UpdateConnectionErrors[keyof UpdateConnectionErrors];

export type UpdateConnectionResponses = {
    /**
     * Successful Response
     */
    200: ConnectionsModel;
};

export type UpdateConnectionResponse = UpdateConnectionResponses[keyof UpdateConnectionResponses];

export type GetConnectionStatusData = {
    body?: never;
    path: {
        /**
         * Connection Uid
         */
        connection_uid: string;
    };
    query?: never;
    url: '/connections/{connection_uid}/status';
};

export type GetConnectionStatusErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetConnectionStatusError = GetConnectionStatusErrors[keyof GetConnectionStatusErrors];

export type GetConnectionStatusResponses = {
    /**
     * Successful Response
     */
    200: ConnectionStatusModel;
};

export type GetConnectionStatusResponse = GetConnectionStatusResponses[keyof GetConnectionStatusResponses];

export type UploadFileData = {
    body: BodyUploadFile;
    path?: never;
    query?: never;
    url: '/bucket';
};

export type UploadFileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadFileError = UploadFileErrors[keyof UploadFileErrors];

export type UploadFileResponses = {
    /**
     * Successful Response
     */
    200: BucketModel;
};

export type UploadFileResponse = UploadFileResponses[keyof UploadFileResponses];

export type GetSchemasData = {
    body?: never;
    path: {
        /**
         * Connection Id
         */
        connection_id: string;
    };
    query?: never;
    url: '/connection/{connection_id}/schema';
};

export type GetSchemasErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSchemasError = GetSchemasErrors[keyof GetSchemasErrors];

export type GetSchemasResponses = {
    /**
     * Successful Response
     */
    200: SchemaModelList;
};

export type GetSchemasResponse = GetSchemasResponses[keyof GetSchemasResponses];

export type GetTablesData = {
    body?: never;
    path: {
        /**
         * Connection Id
         */
        connection_id: string;
    };
    query?: {
        /**
         * Schema
         */
        schema?: string | null;
    };
    url: '/connection/{connection_id}/table';
};

export type GetTablesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTablesError = GetTablesErrors[keyof GetTablesErrors];

export type GetTablesResponses = {
    /**
     * Successful Response
     */
    200: TableModelList;
};

export type GetTablesResponse = GetTablesResponses[keyof GetTablesResponses];

export type GetEntityColumnsData = {
    body?: never;
    path: {
        /**
         * Connection Id
         */
        connection_id: string;
        /**
         * Entity Name
         */
        entity_name: string;
    };
    query?: {
        /**
         * Schema
         */
        schema?: string | null;
        /**
         * Include Row Count
         */
        include_row_count?: boolean;
    };
    url: '/connection/{connection_id}/entities/{entity_name}/columns';
};

export type GetEntityColumnsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEntityColumnsError = GetEntityColumnsErrors[keyof GetEntityColumnsErrors];

export type GetEntityColumnsResponses = {
    /**
     * Successful Response
     */
    200: TableSchemaModel;
};

export type GetEntityColumnsResponse = GetEntityColumnsResponses[keyof GetEntityColumnsResponses];

export type GetEntityRowsData = {
    body?: never;
    path: {
        /**
         * Connection Id
         */
        connection_id: string;
        /**
         * Entity Name
         */
        entity_name: string;
    };
    query?: {
        /**
         * Schema
         */
        schema?: string | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number | null;
        /**
         * After
         */
        after?: string | null;
        /**
         * Order By
         */
        order_by?: string | null;
    };
    url: '/connection/{connection_id}/entities/{entity_name}/rows';
};

export type GetEntityRowsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEntityRowsError = GetEntityRowsErrors[keyof GetEntityRowsErrors];

export type GetEntityRowsResponses = {
    /**
     * Successful Response
     */
    200: RowPageModel;
};

export type GetEntityRowsResponse = GetEntityRowsResponses[keyof GetEntityRowsResponses];

export type ExecuteQueryData = {
    body?: never;
    path: {
        /**
         * Connection Id
         */
        connection_id: string;
        /**
         * Entity Name
         */
        entity_name: string;
    };
    query: {
        /**
         * Query
         */
        query: string;
        /**
         * Limit
         */
        limit?: number | null;
        /**
         * Offset
         */
        offset?: number | null;
        /**
         * Schema
         */
        schema?: string | null;
        /**
         * Allow Writes
         */
        allow_writes?: boolean;
    };
    url: '/connection/{connection_id}/entities/{entity_name}/queries';
};

export type ExecuteQueryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExecuteQueryError = ExecuteQueryErrors[keyof ExecuteQueryErrors];

export type ExecuteQueryResponses = {
    /**
     * Successful Response
     */
    200: QueryResult;
};

export type ExecuteQueryResponse = ExecuteQueryResponses[keyof ExecuteQueryResponses];

export type ExplainQueryData = {
    body?: never;
    path: {
        /**
         * Connection Id
         */
        connection_id: string;
        /**
         * Entity Name
         */
        entity_name: string;
    };
    query: {
        /**
         * Query
         */
        query: string;
    };
    url: '/connection/{connection_id}/entities/{entity_name}/explain';
};

export type ExplainQueryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExplainQueryError = ExplainQueryErrors[keyof ExplainQueryErrors];

export type ExplainQueryResponses = {
    /**
     * Successful Response
     */
    200: QueryInsightModel;
};

export type ExplainQueryResponse = ExplainQueryResponses[keyof ExplainQueryResponses];

export type GetEntityStatsData = {
    body?: never;
    path: {
        /**
         * Connection Id
         */
        connection_id: string;
        /**
         * Entity Name
         */
        entity_name: string;
    };
    query?: {
        /**
         * Schema
         */
        schema?: string | null;
        /**
         * Top Values
         */
        top_values?: boolean;
        /**
         * Sample
         */
        sample?: number;
    };
    url: '/connection/{connection_id}/entities/{entity_name}/stats';
};

export type GetEntityStatsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEntityStatsError = GetEntityStatsErrors[keyof GetEntityStatsErrors];

export type GetEntityStatsResponses = {
    /**
     * Successful Response
     */
    200: TableStatsModel;
};

export type GetEntityStatsResponse = GetEntityStatsResponses[keyof GetEntityStatsResponses];

export type ExportEntityData = {
    body?: never;
    path: {
        /**
         * Connection Id
         */
        connection_id: string;
        /**
         * Entity Name
         */
        entity_name: string;
    };
    query?: {
        /**
         * Schema
         */
        schema?: string | null;
        /**
         * Query
         */
        query?: string | null;
        /**
         * Columns
         */
        columns?: string | null;
        /**
         * Format
         */
        format?: string;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/connection/{connection_id}/entities/{entity_name}/export';
};

export type ExportEntityErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExportEntityError = ExportEntityErrors[keyof ExportEntityErrors];

export type ExportEntityResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SendAdHocRequestData = {
    body: RequestSpecModel;
    path?: never;
    query?: never;
    url: '/request';
};

export type SendAdHocRequestErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SendAdHocRequestError = SendAdHocRequestErrors[keyof SendAdHocRequestErrors];

export type SendAdHocRequestResponses = {
    /**
     * Successful Response
     */
    200: RequestResultModel;
};

export type SendAdHocRequestResponse = SendAdHocRequestResponses[keyof SendAdHocRequestResponses];

export type SendRequestData = {
    body: RequestSpecModel;
    path: {
        /**
         * Connection Id
         */
        connection_id: string;
    };
    query?: never;
    url: '/connection/{connection_id}/request';
};

export type SendRequestErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SendRequestError = SendRequestErrors[keyof SendRequestErrors];

export type SendRequestResponses = {
    /**
     * Successful Response
     */
    200: RequestResultModel;
};

export type SendRequestResponse = SendRequestResponses[keyof SendRequestResponses];

export type ListRequestsData = {
    body?: never;
    path: {
        /**
         * Connection Id
         */
        connection_id: string;
    };
    query?: never;
    url: '/connection/{connection_id}/requests';
};

export type ListRequestsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListRequestsError = ListRequestsErrors[keyof ListRequestsErrors];

export type ListRequestsResponses = {
    /**
     * Successful Response
     */
    200: SavedRequestListModel;
};

export type ListRequestsResponse = ListRequestsResponses[keyof ListRequestsResponses];

export type CreateRequestData = {
    body: RequestSpecModel;
    path: {
        /**
         * Connection Id
         */
        connection_id: string;
    };
    query?: never;
    url: '/connection/{connection_id}/requests';
};

export type CreateRequestErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateRequestError = CreateRequestErrors[keyof CreateRequestErrors];

export type CreateRequestResponses = {
    /**
     * Successful Response
     */
    200: SavedRequestModel;
};

export type CreateRequestResponse = CreateRequestResponses[keyof CreateRequestResponses];

export type DeleteRequestData = {
    body?: never;
    path: {
        /**
         * Connection Id
         */
        connection_id: string;
        /**
         * Request Uid
         */
        request_uid: string;
    };
    query?: never;
    url: '/connection/{connection_id}/requests/{request_uid}';
};

export type DeleteRequestErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteRequestError = DeleteRequestErrors[keyof DeleteRequestErrors];

export type DeleteRequestResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteRequestResponse = DeleteRequestResponses[keyof DeleteRequestResponses];

export type GetRequestData = {
    body?: never;
    path: {
        /**
         * Connection Id
         */
        connection_id: string;
        /**
         * Request Uid
         */
        request_uid: string;
    };
    query?: never;
    url: '/connection/{connection_id}/requests/{request_uid}';
};

export type GetRequestErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRequestError = GetRequestErrors[keyof GetRequestErrors];

export type GetRequestResponses = {
    /**
     * Successful Response
     */
    200: SavedRequestModel;
};

export type GetRequestResponse = GetRequestResponses[keyof GetRequestResponses];

export type UpdateRequestData = {
    body: RequestSpecModel;
    path: {
        /**
         * Connection Id
         */
        connection_id: string;
        /**
         * Request Uid
         */
        request_uid: string;
    };
    query?: never;
    url: '/connection/{connection_id}/requests/{request_uid}';
};

export type UpdateRequestErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateRequestError = UpdateRequestErrors[keyof UpdateRequestErrors];

export type UpdateRequestResponses = {
    /**
     * Successful Response
     */
    200: SavedRequestModel;
};

export type UpdateRequestResponse = UpdateRequestResponses[keyof UpdateRequestResponses];

export type GetVariablesData = {
    body?: never;
    path: {
        /**
         * Connection Id
         */
        connection_id: string;
    };
    query?: never;
    url: '/connection/{connection_id}/variables';
};

export type GetVariablesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetVariablesError = GetVariablesErrors[keyof GetVariablesErrors];

export type GetVariablesResponses = {
    /**
     * Successful Response
     */
    200: VariablesModel;
};

export type GetVariablesResponse = GetVariablesResponses[keyof GetVariablesResponses];

export type SetVariablesData = {
    body: VariablesModel;
    path: {
        /**
         * Connection Id
         */
        connection_id: string;
    };
    query?: never;
    url: '/connection/{connection_id}/variables';
};

export type SetVariablesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetVariablesError = SetVariablesErrors[keyof SetVariablesErrors];

export type SetVariablesResponses = {
    /**
     * Successful Response
     */
    200: VariablesModel;
};

export type SetVariablesResponse = SetVariablesResponses[keyof SetVariablesResponses];

export type GetSlowQueriesData = {
    body?: never;
    path: {
        /**
         * Connection Id
         */
        connection_id: string;
    };
    query?: {
        /**
         * Limit
         */
        limit?: number | null;
        /**
         * Order By
         */
        order_by?: string;
    };
    url: '/connection/{connection_id}/slow-queries';
};

export type GetSlowQueriesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSlowQueriesError = GetSlowQueriesErrors[keyof GetSlowQueriesErrors];

export type GetSlowQueriesResponses = {
    /**
     * Successful Response
     */
    200: SlowQueryReportModel;
};

export type GetSlowQueriesResponse = GetSlowQueriesResponses[keyof GetSlowQueriesResponses];

export type ListSnapshotsData = {
    body?: never;
    path: {
        /**
         * Connection Id
         */
        connection_id: string;
    };
    query?: never;
    url: '/connection/{connection_id}/slow-queries/snapshots';
};

export type ListSnapshotsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListSnapshotsError = ListSnapshotsErrors[keyof ListSnapshotsErrors];

export type ListSnapshotsResponses = {
    /**
     * Successful Response
     */
    200: SnapshotListModel;
};

export type ListSnapshotsResponse = ListSnapshotsResponses[keyof ListSnapshotsResponses];

export type TakeSnapshotData = {
    body?: never;
    path: {
        /**
         * Connection Id
         */
        connection_id: string;
    };
    query?: {
        /**
         * Note
         */
        note?: string;
    };
    url: '/connection/{connection_id}/slow-queries/snapshots';
};

export type TakeSnapshotErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TakeSnapshotError = TakeSnapshotErrors[keyof TakeSnapshotErrors];

export type TakeSnapshotResponses = {
    /**
     * Successful Response
     */
    200: SnapshotDetailModel;
};

export type TakeSnapshotResponse = TakeSnapshotResponses[keyof TakeSnapshotResponses];

export type DeleteSnapshotData = {
    body?: never;
    path: {
        /**
         * Connection Id
         */
        connection_id: string;
        /**
         * Snapshot Uid
         */
        snapshot_uid: string;
    };
    query?: never;
    url: '/connection/{connection_id}/slow-queries/snapshots/{snapshot_uid}';
};

export type DeleteSnapshotErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteSnapshotError = DeleteSnapshotErrors[keyof DeleteSnapshotErrors];

export type DeleteSnapshotResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteSnapshotResponse = DeleteSnapshotResponses[keyof DeleteSnapshotResponses];

export type GetSnapshotData = {
    body?: never;
    path: {
        /**
         * Connection Id
         */
        connection_id: string;
        /**
         * Snapshot Uid
         */
        snapshot_uid: string;
    };
    query?: never;
    url: '/connection/{connection_id}/slow-queries/snapshots/{snapshot_uid}';
};

export type GetSnapshotErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSnapshotError = GetSnapshotErrors[keyof GetSnapshotErrors];

export type GetSnapshotResponses = {
    /**
     * Successful Response
     */
    200: SnapshotDetailModel;
};

export type GetSnapshotResponse = GetSnapshotResponses[keyof GetSnapshotResponses];

export type CompareSnapshotsData = {
    body?: never;
    path: {
        /**
         * Connection Id
         */
        connection_id: string;
    };
    query: {
        /**
         * Before
         */
        before: string;
        /**
         * After
         */
        after?: string | null;
    };
    url: '/connection/{connection_id}/slow-queries/compare';
};

export type CompareSnapshotsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CompareSnapshotsError = CompareSnapshotsErrors[keyof CompareSnapshotsErrors];

export type CompareSnapshotsResponses = {
    /**
     * Successful Response
     */
    200: SnapshotComparisonModel;
};

export type CompareSnapshotsResponse = CompareSnapshotsResponses[keyof CompareSnapshotsResponses];

export type ListFlowsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/flows';
};

export type ListFlowsResponses = {
    /**
     * Successful Response
     */
    200: FlowListModel;
};

export type ListFlowsResponse = ListFlowsResponses[keyof ListFlowsResponses];

export type CreateFlowData = {
    body: FlowSpecModel;
    path?: never;
    query?: never;
    url: '/flows';
};

export type CreateFlowErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateFlowError = CreateFlowErrors[keyof CreateFlowErrors];

export type CreateFlowResponses = {
    /**
     * Successful Response
     */
    200: FlowModel;
};

export type CreateFlowResponse = CreateFlowResponses[keyof CreateFlowResponses];

export type DeleteFlowData = {
    body?: never;
    path: {
        /**
         * Flow Uid
         */
        flow_uid: string;
    };
    query?: never;
    url: '/flows/{flow_uid}';
};

export type DeleteFlowErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteFlowError = DeleteFlowErrors[keyof DeleteFlowErrors];

export type DeleteFlowResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteFlowResponse = DeleteFlowResponses[keyof DeleteFlowResponses];

export type GetFlowData = {
    body?: never;
    path: {
        /**
         * Flow Uid
         */
        flow_uid: string;
    };
    query?: never;
    url: '/flows/{flow_uid}';
};

export type GetFlowErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetFlowError = GetFlowErrors[keyof GetFlowErrors];

export type GetFlowResponses = {
    /**
     * Successful Response
     */
    200: FlowModel;
};

export type GetFlowResponse = GetFlowResponses[keyof GetFlowResponses];

export type UpdateFlowData = {
    body: FlowSpecModel;
    path: {
        /**
         * Flow Uid
         */
        flow_uid: string;
    };
    query?: never;
    url: '/flows/{flow_uid}';
};

export type UpdateFlowErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateFlowError = UpdateFlowErrors[keyof UpdateFlowErrors];

export type UpdateFlowResponses = {
    /**
     * Successful Response
     */
    200: FlowModel;
};

export type UpdateFlowResponse = UpdateFlowResponses[keyof UpdateFlowResponses];

export type TestNodeData = {
    body?: never;
    path: {
        /**
         * Flow Uid
         */
        flow_uid: string;
        /**
         * Node Id
         */
        node_id: string;
    };
    query?: never;
    url: '/flows/{flow_uid}/nodes/{node_id}/test';
};

export type TestNodeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TestNodeError = TestNodeErrors[keyof TestNodeErrors];

export type TestNodeResponses = {
    /**
     * Successful Response
     */
    200: NodeTestModel;
};

export type TestNodeResponse = TestNodeResponses[keyof TestNodeResponses];

export type DeleteKeyData = {
    body?: never;
    path: {
        /**
         * Connection Id
         */
        connection_id: string;
    };
    query: {
        /**
         * Key
         */
        key: string;
    };
    url: '/connection/{connection_id}/redis/keys';
};

export type DeleteKeyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteKeyError = DeleteKeyErrors[keyof DeleteKeyErrors];

export type DeleteKeyResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteKeyResponse = DeleteKeyResponses[keyof DeleteKeyResponses];

export type ScanKeysData = {
    body?: never;
    path: {
        /**
         * Connection Id
         */
        connection_id: string;
    };
    query?: {
        /**
         * Pattern
         */
        pattern?: string;
        /**
         * Cursor
         */
        cursor?: number;
        /**
         * Count
         */
        count?: number | null;
    };
    url: '/connection/{connection_id}/redis/keys';
};

export type ScanKeysErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScanKeysError = ScanKeysErrors[keyof ScanKeysErrors];

export type ScanKeysResponses = {
    /**
     * Successful Response
     */
    200: RedisKeyListModel;
};

export type ScanKeysResponse = ScanKeysResponses[keyof ScanKeysResponses];

export type ReadKeyData = {
    body?: never;
    path: {
        /**
         * Connection Id
         */
        connection_id: string;
    };
    query: {
        /**
         * Key
         */
        key: string;
    };
    url: '/connection/{connection_id}/redis/keys/value';
};

export type ReadKeyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadKeyError = ReadKeyErrors[keyof ReadKeyErrors];

export type ReadKeyResponses = {
    /**
     * Successful Response
     */
    200: RedisKeyValueModel;
};

export type ReadKeyResponse = ReadKeyResponses[keyof ReadKeyResponses];

export type ServerInfoData = {
    body?: never;
    path: {
        /**
         * Connection Id
         */
        connection_id: string;
    };
    query?: never;
    url: '/connection/{connection_id}/redis/info';
};

export type ServerInfoErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ServerInfoError = ServerInfoErrors[keyof ServerInfoErrors];

export type ServerInfoResponses = {
    /**
     * Successful Response
     */
    200: RedisInfoModel;
};

export type ServerInfoResponse = ServerInfoResponses[keyof ServerInfoResponses];

export type ListChannelsData = {
    body?: never;
    path: {
        /**
         * Connection Id
         */
        connection_id: string;
    };
    query?: {
        /**
         * Pattern
         */
        pattern?: string;
    };
    url: '/connection/{connection_id}/redis/channels';
};

export type ListChannelsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListChannelsError = ListChannelsErrors[keyof ListChannelsErrors];

export type ListChannelsResponses = {
    /**
     * Successful Response
     */
    200: RedisChannelListModel;
};

export type ListChannelsResponse = ListChannelsResponses[keyof ListChannelsResponses];

export type PublishData = {
    body?: never;
    path: {
        /**
         * Connection Id
         */
        connection_id: string;
    };
    query: {
        /**
         * Channel
         */
        channel: string;
        /**
         * Message
         */
        message?: string;
    };
    url: '/connection/{connection_id}/redis/publish';
};

export type PublishErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PublishError = PublishErrors[keyof PublishErrors];

export type PublishResponses = {
    /**
     * Successful Response
     */
    200: RedisPublishResultModel;
};

export type PublishResponse = PublishResponses[keyof PublishResponses];

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
